# Site settings
title: Elizabeth McDaniel, PhD
general_email: elizabethmcd93@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Microbial Ecology, Biotechnology, Multi-Omics

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://pragyadas05.github.io" # the base hostname & protocol for your site

github_username: pragyadas0592
twitter_username: lizilla93
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
