# Site settings
title: Pragya Das, M.Sc
general_email: pragyadas0592@yahoo.com

description: > # this means to ignore newlines until "baseurl:"
  Remote Sensing, Environmental Health and Safety, Disaster Management, Satellite Image Processing

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://pragyadas0592.github.io" # the base hostname & protocol for your site

github_username: pragyadas0592
twitter_username: 
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
